
// Device data sync
export const DOWNLOADED_RECIPES = "DOWNLOADED_RECIPES";
export const ADD_RECIPE = "ADD_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const EDIT_INGREDIENT = "EDIT_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const DOWNLOADED_INGREDIENTS = "DOWNLOADED_INGREDIENTS";

// Login info
export const LOADED_LOGIN_INFO = "LOADED_LOGIN_INFO";

// Sensors
export const DOWNLOADED_SENSORS_FILE = "DOWNLOADED_SENSORS_FILE";
export const DOWNLOADED_SENSOR_DATA_ALL = "DOWNLOADED_SENSOR_DATA_ALL";
export const DOWNLOADED_SENSOR_DATE_DATA = "DOWNLOADED_SENSOR_DATE_DATA";
export const SENSOR_UPDATE = "SENSOR_UPDATE";